# Generated by Django 5.2.5 on 2025-08-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_sign_in_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
