# Generated by Django 5.2.5 on 2025-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking_created_at_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='showDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
