# Generated by Django 5.2.5 on 2025-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shows_showdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='showDateTime',
            field=models.CharField(blank=True, null=True),
        ),
    ]
