# Generated by Django 5.2.5 on 2025-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shows_showdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
