# Generated by Django 5.2.5 on 2025-09-02 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_booking_id_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(),
        ),
    ]
